version: "3"

services:

    rock-paper-scissors-nginx:
        container_name: rock-paper-scissors-nginx
        build: docker/nginx
        working_dir: /app
        entrypoint:
            - /usr/sbin/nginx
            - -g
            - daemon off;
        volumes:
            - ./:/app
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8888:443
        links:
            - rock-paper-scissors-php-fpm

    rock-paper-scissors-php-fpm:
        container_name: rock-paper-scissors-php-fpm
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                GROUPID: ${GROUPID}
                USERID: ${USERID}
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/php-fpm/php-ini-override/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
        env_file: .env.local


networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"
